export const GET_COMMUNITIES = "GET_COMMUNITIES";
export const GET_ONE_COMMUNITY = "GET_ONE_COMMUNITY";
export const ADD_COMMUNITY = "ADD_COMMUNITY";
export const DELETE_COMMUNITY="DELETE_COMMUNITY";
export const UPDATE_COMMUNITY="UPDATE_COMMUNITY";
